# Common Blocked Ports
# Browsers block a specific list of ports to prevent cross-protocol exploits and malicious probing. Key restricted ports include:
  # 6000: X11 display server
  # 20-21: FTP data and access
  # 22: SSH
  # 109-110: POP2 and POP3
  # 6566: SANE port
  # 10080: Amanda

# Common Blocked Ports Reminder (Keep ports like 5000-5004 free from system service conflicts)

services:
  # =========================================================================
  # MOTEUR DE MIGRATION (S'exécute, applique le SQL brut puis s'arrête en Succès)
  # =========================================================================
  database.migrator:
    image: ${DOCKER_REGISTRY-}database-migrator
    build:
      context: .
      dockerfile: DataBasePostgreSql/Dockerfile
    environment:
      - DB_USERS_CONNECTION=Host=collectorshop-users-postgres;Port=5432;Database=users_db;Username=myuser;Password=mypassword;
      - DB_FINANCE_CONNECTION=Host=collectorshop-finance-postgres;Port=5432;Database=finance_db;Username=myuser;Password=mypassword;
      - DB_COLLECTOR_CONNECTION=Host=collectorshop-collector-postgres;Port=5432;Database=collector_db;Username=myuser;Password=mypassword;
    depends_on:
      users.database:
        condition: service_healthy
      collector.database:
        condition: service_healthy
      finance.database:
        condition: service_healthy

  # API UNIQUE & UNIFIÉE (GRAND PUBLIC + BACKOFFICE)
  collectorshopapi:
    image: ${DOCKER_REGISTRY-}collectorshopapi
    build:
      context: .
      dockerfile: CollectorShopApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - StorageSettings__StorageFolder=/app/user_documents
      - Security__CookieName=CollectorShop_Auth_TK
      - Security__JwtAudience=CollectorShop_SPA
      - Security__JwtSecret=UneCleSuperSecrèteEtTresLonguePourLeHachageDuJwt123456!
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - csharp_document_storage:/app/user_documents # Le volume est conservé pour l'accès aux documents/images
    depends_on:
      users.database:
        condition: service_healthy
      collector.database:
        condition: service_healthy
      finance.database:
        condition: service_healthy
      database.migrator:
        condition: service_started

  # ==========================================
  # 1. BULLE IDENTITÉ & RGPD (Données Personnelles)
  # ==========================================
  users.database:
    image: postgres:17-bookworm
    container_name: collectorshop-users-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # 2. BULLE MÉTIER PUBLIC (Catalogue & Trafic Masse)
  # ==========================================
  collector.database:
    image: postgres:17-bookworm
    container_name: collectorshop-collector-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: collector_db
    ports:
      - "5433:5432"
    volumes:
      - collector_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d collector_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # 3. BULLE HAUTE SÉCURITÉ (Finance, Commission, Audit)
  # ==========================================
  finance.database:
    image: postgres:17-bookworm
    container_name: collectorshop-finance-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: finance_db
    ports:
      - "5434:5432"
    volumes:
      - finance_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # OUTILLAGE DE SUPERVISION DES BASES
  # ==========================================
  adminer:
    image: adminer
    container_name: collectorshop-adminer
    restart: always
    ports:
      - "5431:8080"
    depends_on:
      users.database:
        condition: service_healthy
      collector.database:
        condition: service_healthy
      finance.database:
        condition: service_healthy

volumes:
  users_postgres_data:
  collector_postgres_data:
  finance_postgres_data:
  csharp_document_storage: