@CollectorShopApi_HostAddress_http = http://localhost:5000

GET {{CollectorShopApi_HostAddress_http}}/weatherforecast/
Accept: application/json

###

@CollectorShopApi_HostAddress_https = https://localhost:5001

GET {{CollectorShopApi_HostAddress_https}}/weatherforecast/
Accept: application/json

###
