name: CI/CD DevSecOps Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  audit-security:
    name: Security Scan (SAST & Secrets)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trufflehog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
        continue-on-error: true

  build-and-test:
    name: Compilation & Integration Tests
    runs-on: ubuntu-latest
    needs: audit-security
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Verify Code Compilation
        run: dotnet build --no-restore --configuration Release

      # Pas besoin d'installer Docker ! On utilise directement la version native "docker compose"
      - name: Run Infrastructure & Integration Tests via Docker Compose
        run: |
          docker compose up --build --exit-code-from api.tests

      - name: Shutdown Containers
        if: always()
        run: docker compose down -v
